### PR TITLE
Makes SpTBXLib Dpi-aware

### PR DESCRIPTION
**Pull request by pyscripter**
Firstly, let me just say that even now that Delphi supports Unicode and styles, SpTBXLib is still very useful.  In relation to the management of menus and actions it is what the ActionManager stuff ought to be but never was.   It also contains many improved and new components (Tab controls, color pickers, dock panels to name a few).  So a big thank you for your contribution.

This pull request does the following:
a)  Provides support for the use of SpTBXLib in DPI aware applications.
b)  Improves the support of VCL styles in a few places.
c)  Introduces a couple of changes in TSpTBXToolbar.WMEraseBkgnd and Paint that reduce flicker in conjunction with a change in TB2Item.pas.

The support for DPI awareness is quite comprehensive covering all major aspects of the library.  As a proof of the concept a modified version of the Overview demo is included in this update in the directory Hi-DPI.  You will need a High-DPI monitor (typically found in modern laptops) to test this.  I have tested the changes with a scaling factor of 2.25 and it looks good. 

The same directory contains a unit of mine called Vcl.Styles.DPIAware that scales Vcl styles for use in DPI aware applications, which is used in the Demo.  It also contains slightly modified versions of TB2Item.pas (flicker reduction) and TB2Toolbar.pas (scaling of chevrons).

### CODE REVIEW

**Comment by pyscripter** [comment]
I am closing this since I a have done more work on SpTBXLib in the fork at https://github.com/pyscripter/SpTBXLib.  
Work has also been done on TB2K (see the patch the fork), which is now also DPI aware.
Finally you may want to have a look at the enhancements on your Multisinstaller (https://github.com/pyscripter/MultiInstaller).
I am more than happy for you to incorporate  all the above back into your repository, if you see fit.
Thanks again for the amazing stuff you have done.

**Comment by SilverpointDev** [comment]
Thank you! I think I've added all your changes, can you please test the latest release?

**Comment by pyscripter** [comment]
Will do.  Thanks!

**Comment by pyscripter** [comment]
General impression is very good!   I will report some specific issues (mostly minor) as issues.

**Pull request closed without merging**
